### ISSUE TITLE
Further integration of Icinga elements

### ISSUE THREAD

**Issue by ArthurBorsboom** [patrikskrivanek/icinga2-check_systemd_service#1]
Hi Patrik,

I have started to use your Icinga2 systemd service plugin.

I have created a CheckCommands file and two examples how to use the plugin with the CheckCommands file.

Maybe it is helpful to make this part of the package and share it with the rest of the world ? :)

[check_systemd_service-icinga-configs.zip](https://github.com/patrikskrivanek/icinga2-check_systemd_service/files/4818778/check_systemd_service-icinga-configs.zip)

**Comment by patrikskrivanek** [comment]
Hi @ArthurBorsboom ,

thank you, I am going to implement your example into the repository in a few days :)
