### ISSUE TITLE
some services reported do not exists but present when check is done locally

### ISSUE THREAD

**Issue by mvrgotiks** [patrikskrivanek/icinga2-check_systemd_service#2]
Hi Patrik,

I came across strange issue.

Following the configuration examples, I have configured on for of my hosts checks for the following services:

- firewalld
- icinga2
- vmtoolsd

On all of the hosts, these services are found and their status correctly displayed in IcingaWeb2.

For following services, if I use the plugin form command line it gives exected result, however, in IcingaWeb2 is telling me that that service does not exist:

- httpd
- postgresql-9.6

Here is my host configurations:

```object Host "service-vm1.example.com" {
    vars.group_nl1 = true
    import "generic-host"
    /* Specify the address attributes for checks e.g. `ssh` or `http`. */
    address = "172.16.1.42"
    address6 = ""

    vars.systemd["icinga2"] = { friendly_name = "Service Icinga2 Agent", restart = true }
    vars.systemd["vmtoolsd"] = { friendly_name = "Service VMware Tools", restart = true }
    vars.systemd["firewalld"] = { friendly_name = "Service FirewallD", restart = false }
...
}

object Host "service-vm2.example.com" {
    vars.group_nl1 = true
    import "generic-host"
    /* Specify the address attributes for checks e.g. `ssh` or `http`. */
    address = "172.16.1.44"
    address6 = ""

    vars.systemd["icinga2"] = { friendly_name = "Service Icinga2 Agent", restart = true }
    vars.systemd["vmtoolsd"] = { friendly_name = "Service VMware Tools", restart = false }
    vars.systemd["firewalld"] = { friendly_name = "Service FirewallD", restart = false }

    vars.agent_endpoint = name
    vars.os = "Linux"
...
}

object Host "web-vm1.example.com" {
    vars.group_nl1 = true
    import "generic-host"
    /* Specify the address attributes for checks e.g. `ssh` or `http`. */
    address = "172.16.1.45"
    address6 = ""

    vars.systemd["icinga2"] = { friendly_name = "Service Icinga2 Agent", restart = true }
    vars.systemd["vmtoolsd"] = { friendly_name = "Service VMware Tools", restart = false }
    vars.systemd["firewalld"] = { friendly_name = "Service FirewallD", restart = false }
    vars.systemd["httpd"] = { friendly_name = "Service Apache", restart = false }

    vars.agent_endpoint = name
    vars.os = "Linux"
...
}

object Host "db-vm1.example.com" {
    vars.group_nl1 = true
    import "generic-host"
    /* Specify the address attributes for checks e.g. `ssh` or `http`. */
    address = "172.16.1.43"
    address6 = ""

    vars.systemd["icinga2"] = { friendly_name = "Service Icinga2 Agent", restart = true }
    vars.systemd["vmtoolsd"] = { friendly_name = "Service VMware Tools", restart = false }
    vars.systemd["firewalld"] = { friendly_name = "Service FirewallD", restart = false }
    vars.systemd["postgresql-9.6"] = { friendly_name = "Service PostgreSQL 9.6 database server", restart = false }

    vars.agent_endpoint = name
    vars.os = "Linux"
...
}

```

Any ideas?
Let me know if I can provide more helpful data.

**Comment by patrikskrivanek** [comment]
Hello @mvrgotiks, the service name must match the service in the service list.. first of all you should check the list of available services with `systemctl list-units --type=service` if there is a service you are looking for.. secondly you should make sure that your service is enabled..

**Comment by mvrgotiks** [comment]
Hi Patrik,

Indeed, all works as expected. I haven’t set command_endpoint when configuring service, which resulted in check executing only on satellite and not on endpoints ☺️


— — —
Met vriendelijke groet / Best regards,

Marko Vrgotic
Sr. System Engineer
ActiveVideo

Tel. +31 (0)35 677 4131
email: m.vrgotic@activevideo.com
www.activevideo.com
________________________________

**Comment by qwertiko** [comment]
I've ran into the same problem mentioned in this issue. I'd suggest to add `command_endpoint = ` to the service example in the readme.

**Comment by mattboston** [comment]
I'm having the same issue.  I have around a dozen CentOS 8 servers that run identical services that are also on CentOS 7.  The ones on CentOS 7 work fine, but CentOS 8 they do not.  No matter the OS, I can run from the command line and it always succeeds.

Here's the command I'm using for one of the servers:
`/usr/lib64/nagios/plugins/check_systemd_service gitlab-runsvdir.service`

And the output:
`ERROR: service gitlab-runsvdir.service doesn't exist`

**Comment by mvrgotiks** [comment]
Check the selinux flag as well, for majority of my checks I needed to execute:
chcon -t nagios_unconfined_plugin_exec_t <check_name>

Also do not forget to set command_endpoint in service definition, as mentioned above.

-----
kind regards/met vriendelijke groeten

Marko Vrgotic
Sr. System Engineer @ System Administration

ActiveVideo



From: Matt Shields ***@***.***>
Date: Tuesday, 29 June 2021 at 19:22
To: patrikskrivanek/icinga2-check_systemd_service ***@***.***>
Cc: Marko Vrgotic ***@***.***>, Mention ***@***.***>
Subject: Re: [patrikskrivanek/icinga2-check_systemd_service] some services reported do not exists but present when check is done locally (#2)

***CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender!!!***

I'm having the same issue. I have around a dozen CentOS 8 servers that run identical services that are also on CentOS 7. The ones on CentOS 7 work fine, but CentOS 8 they do not. No matter the OS, I can run from the command line and it always succeeds.

Here's the command I'm using for one of the servers:
/usr/lib64/nagios/plugins/check_systemd_service gitlab-runsvdir.service

And the output:
ERROR: service gitlab-runsvdir.service doesn't exist

**Comment by mattboston** [comment]
I'm fairly new to Icinga2 (previously used Icinga and Nagios), what's the command_endpoint for?  I'll also check the selinux settings

**Comment by mattboston** [comment]
The file already had the correct selinux attributes:
`system_u:object_r:nagios_unconfined_plugin_exec_t:s0 check_systemd_service`

**Comment by mvrgotiks** [comment]
The command_endpoint tells the icinga where the command should be executed, or which node, whether master/satellite or agent needs to run it. Also, that check_command needs to exist on the machine where it's going to be executed.

**Comment by mvrgotiks** [comment]
In my particular service config for this check, it looks like this:
```
apply Service for (service_name => config in host.vars.systemd) {
    import "generic-service"
    check_command = "systemd_service"
    display_name = config.friendly_name
    vars.systemd_service_name = service_name
    vars.systemd_restart = config.restart
    command_endpoint = host.vars.agent_endpoint    <==  
    vars.grafana_graph_disable = true
    assign where host.vars.systemd != null
}
```

**Comment by mattboston** [comment]
Yes, the command gets pushed to all the servers with a Salt state and permissions are set correctly.

ah.  command_endpoint is set to host_name in the generic-service template

**Comment by mattboston** [comment]
If I check the cli api, the command_endpoint resolves to the hostname which is also the endpoint.  So this check and others are also running on the destination server.

**Comment by mattboston** [comment]
Here's a few other things I did to debug.

1. Inserted "echo `hostname`" to line 110.  This correctly added the servers hostname to the output in icingaweb.
2. Inserted "echo `systemctl list-units --type=service | grep gitlab`" to line 111.  This gave me the following output, so it appears that selinux might be killing the check.

`<Timeout exceeded.><Terminated by signal 9 (Killed).>`

**Comment by mattboston** [comment]
I was able to solve by running w/ sudo.
