### ISSUE TITLE
OneShot Services are not supported

### ISSUE THREAD

**Issue by uvu9Ba** [patrikskrivanek/icinga2-check_systemd_service#3]
OneShot services are only active while running and not enabled. The rest of the time they are inactive.

For example this backup services
```
myhost # systemctl cat restic-backup@daily.service
# /etc/systemd/system/restic-backup@.service
[Unit]
Description = Create backups with restic (%i)
Documentation = man:restic(1)

[Service]
Type = oneshot
EnvironmentFile = /etc/restic/%i.conf
ExecStart = /usr/bin/restic backup --verbose $TAGS $ONE_FILESYSTEM $CACHE $BACKUP_EXCLUDES $BACKUP_PATHS
Nice=10

[Install]
WantedBy = multi-user.target
```

Will be triggered by this timer:
```
myhost ~ # systemctl cat restic-backup@daily.timer
# /etc/systemd/system/restic-backup@daily.timer
[Unit]
Description = Timer for backups with restic (%i)

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
```

Status of this service is normally
```
myhost ~ # systemctl status restic-backup@daily.service
● restic-backup@daily.service - Create backups with restic (daily)
   Loaded: loaded (/etc/systemd/system/restic-backup@.service; disabled; vendor preset: disabled)
   Active: inactive (dead) since Mo 2021-01-11 00:02:42 CET; 16h ago
```

As workaround for active/inactive status check the `RemainAfterExit` would be help but the service is still not enabled.
```
https://www.freedesktop.org/software/systemd/man/systemd.service.html
RemainAfterExit=
Takes a boolean value that specifies whether the service shall be considered active even when all its processes exited. Defaults to no.
```

**Comment by patrikskrivanek** [comment]
Hello,

I am not planning to (just now) implement this feature into the program. The main task of the program is monitoring running & enabled services. If you are interested in this topic, you can create your own solution and do a merge request. Otherwise it will be implemented in the future as a part of bigger package of changes.

Best regards

**Comment by patrikskrivanek** [comment]
now supported in v1.2.0 (https://github.com/patrikskrivanek/icinga2-check_systemd_service/releases/tag/v1.2.0)
