### ISSUE TITLE
icinga director command def.

### ISSUE THREAD

**Issue by haytxy** [patrikskrivanek/icinga2-check_systemd_service#4]
Hello,

are you able to provide settings for the Icinga director?  How to define the command for this check_systemd_service ?
Trying in every variant but the result is the same: Check command 'check_systemd_service' does not exist.

example
![image](https://user-images.githubusercontent.com/79607995/109070005-4400d300-76f2-11eb-97f0-efc1d05c667f.png)
![image](https://user-images.githubusercontent.com/79607995/109070040-4e22d180-76f2-11eb-8bb3-3c006aa4baeb.png)

**Comment by patrikskrivanek** [comment]
Hello,

It might be because of name colision. The name of command should be systemd_service not check_systemd_service (it is the name of monitorign script). 

Check out README
